version: "3"

networks:
  uptime:
    external: true
  
volumes:
  uptime_data:
    external: yes

services:
  kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - USER_UID=$USER_UID
      - USER_GID=$USER_GID
    restart: always
    networks:
      - uptime
    volumes:
      - uptime_data:/app/data
    ports:
      - "3001:3001"